HOSTS = [
    {
        "id": "marco",
        "name": "Marco",
        "language": "it",
        "emoji": "👨‍🍳",
        "imageUrl": "/hosts/marco-1.jpg",
        "descriptionEn": "A passionate Roman chef who brings Italian to life through the kitchen.",
        "descriptionDa": "En passioneret romersk kok, der bringer italiensk til live gennem køkkenet.",
        "descriptionIt": "Uno chef romano appassionato che dà vita all'italiano attraverso la cucina.",
        "descriptionEs": "Un apasionado chef romano que da vida al italiano a través de la cocina.",
        "greetingEn": "Ciao! Let's cook up some beautiful Italian words together!",
        "greetingDa": "Ciao! Lad os lave nogle smukke italienske ord sammen!",
        "greetingIt": "Ciao! Cuciniamo insieme delle belle parole italiane!",
        "greetingEs": "¡Ciao! ¡Cocinemos juntos unas hermosas palabras italianas!",
        "color": "red",
        "voice": {"voiceName": "it-IT-DiegoNeural"},
    },
    {
        "id": "giulia",
        "name": "Giulia",
        "language": "it",
        "emoji": "👩‍🏫",
        "imageUrl": "/hosts/giulia-1.jpg",
        "descriptionEn": "An elegant Florentine professor with a love for precise pronunciation.",
        "descriptionDa": "En elegant florentinsk professor med kærlighed til præcis udtale.",
        "descriptionIt": "Un'elegante professoressa fiorentina con la passione per la pronuncia perfetta.",
        "descriptionEs": "Una elegante profesora florentina con pasión por la pronunciación perfecta.",
        "greetingEn": "Buongiorno! Let's perfect your Italian pronunciation today.",
        "greetingDa": "Buongiorno! Lad os perfektionere din italienske udtale i dag.",
        "greetingIt": "Buongiorno! Perfezzioniamo insieme la tua pronuncia italiana oggi.",
        "greetingEs": "¡Buongiorno! Perfeccionemos tu pronunciación italiana hoy.",
        "color": "blue",
        "voice": {"voiceName": "it-IT-IsabellaNeural"},
    },
    {
        "id": "luca",
        "name": "Luca",
        "language": "it",
        "emoji": "🧑‍🎤",
        "imageUrl": "/hosts/luca-1.jpg",
        "descriptionEn": "An energetic Milanese student who makes learning Italian fun and casual.",
        "descriptionDa": "En energisk milanesisk studerende, der gør det sjovt at lære italiensk.",
        "descriptionIt": "Uno studente milanese pieno di energia che rende l'italiano divertente e informale.",
        "descriptionEs": "Un estudiante milanés lleno de energía que hace que aprender italiano sea divertido e informal.",
        "greetingEn": "Ehi! Ready to sound like a true Italian? Let's go!",
        "greetingDa": "Ehi! Klar til at lyde som en ægte italiener? Lad os komme i gang!",
        "greetingIt": "Ehi! Pronto a parlare come un vero italiano? Andiamo!",
        "greetingEs": "¡Ehi! ¿Listo para sonar como un verdadero italiano? ¡Vamos!",
        "color": "purple",
        "voice": {"voiceName": "it-IT-GiuseppeMultilingualNeural"},
    },
    {
        "id": "sofia",
        "name": "Sofia",
        "language": "it",
        "emoji": "👵",
        "imageUrl": "/hosts/sofia-1.jpg",
        "descriptionEn": "A warm Neapolitan nonna who teaches through stories and tradition.",
        "descriptionDa": "En varm napolitansk bedstemor, der underviser gennem historier og tradition.",
        "descriptionIt": "Una calda nonna napoletana che insegna attraverso storie e tradizioni.",
        "descriptionEs": "Una cálida abuela napolitana que enseña a través de historias y tradiciones.",
        "greetingEn": "Benvenuto, tesoro! Let me share the beauty of our language with you.",
        "greetingDa": "Benvenuto, tesoro! Lad mig dele skønheden ved vores sprog med dig.",
        "greetingIt": "Benvenuto, tesoro! Lascia che ti mostri la bellezza della nostra lingua.",
        "greetingEs": "¡Benvenuto, tesoro! Déjame compartir la belleza de nuestro idioma contigo.",
        "color": "amber",
        "voice": {"voiceName": "it-IT-ElsaNeural"},
    },
    {
        "id": "anders",
        "name": "Anders",
        "language": "da",
        "emoji": "🧔‍♂️",
        "imageUrl": "/hosts/anders-1.jpg",
        "descriptionEn": "A Copenhagen barista who teaches Danish through hygge culture and coffee.",
        "descriptionDa": "En københavnsk barista, der underviser i dansk gennem hyggekultur og kaffe.",
        "descriptionIt": "Un barista di Copenaghen che insegna il danese attraverso la cultura hygge e il caffè.",
        "descriptionEs": "Un barista de Copenhague que enseña danés a través de la cultura hygge y el café.",
        "greetingEn": "Hej! Grab a coffee and let's learn some Danish together!",
        "greetingDa": "Hej! Tag en kop kaffe, og lad os lære noget dansk sammen!",
        "greetingIt": "Hej! Prendi un caffè e impariamo un po' di danese insieme!",
        "greetingEs": "¡Hej! ¡Toma un café y aprendamos algo de danés juntos!",
        "color": "teal",
        "voice": {"voiceName": "da-DK-JeppeNeural"},
    },
    {
        "id": "freja",
        "name": "Freja",
        "language": "da",
        "emoji": "👩‍🦰",
        "imageUrl": "/hosts/freja-1.jpg",
        "descriptionEn": "An Aarhus librarian with a passion for Nordic literature and clear speech.",
        "descriptionDa": "En bibliotekar fra Aarhus med passion for nordisk litteratur og tydelig tale.",
        "descriptionIt": "Una bibliotecaria di Aarhus appassionata di letteratura nordica e dizione chiara.",
        "descriptionEs": "Una bibliotecaria de Aarhus apasionada por la literatura nórdica y la dicción clara.",
        "greetingEn": "Velkommen! Let me guide you through the beauty of Danish words.",
        "greetingDa": "Velkommen! Lad mig guide dig gennem de smukke danske ord.",
        "greetingIt": "Velkommen! Lascia che ti guidi attraverso la bellezza delle parole danesi.",
        "greetingEs": "¡Velkommen! Déjame guiarte a través de la belleza de las palabras danesas.",
        "color": "indigo",
        "voice": {"voiceName": "da-DK-ChristelNeural"},
    },
    {
        "id": "mikkel",
        "name": "Mikkel",
        "language": "da",
        "emoji": "👱‍♂️",
        "imageUrl": "/hosts/mikkel-1.jpg",
        "descriptionEn": "An Odense student fascinated by Danish design and modern culture.",
        "descriptionDa": "En studerende fra Odense, fascineret af dansk design og moderne kultur.",
        "descriptionIt": "Uno studente di Odense affascinato dal design danese e dalla cultura moderna.",
        "descriptionEs": "Un estudiante de Odense fascinado por el diseño danés y la cultura moderna.",
        "greetingEn": "Hej hej! Ready to discover Danish? It's easier than you think!",
        "greetingDa": "Hej hej! Klar til at opdage dansk? Det er nemmere end du tror!",
        "greetingIt": "Hej hej! Pronto a scoprire il danese? È più facile di quanto pensi!",
        "greetingEs": "¡Hej hej! ¿Listo para descubrir el danés? ¡Es más fácil de lo que piensas!",
        "color": "cyan",
        "voice": {"voiceName": "da-DK-JeppeNeural"},
    },
    {
        "id": "ingrid",
        "name": "Ingrid",
        "language": "da",
        "emoji": "👩‍🦳",
        "imageUrl": "/hosts/ingrid-1.jpg",
        "descriptionEn": "A Jutland grandmother who teaches through Danish traditions and warmth.",
        "descriptionDa": "En jysk bedstemor, der underviser gennem danske traditioner og varme.",
        "descriptionIt": "Una nonna dello Jutland che insegna attraverso le tradizioni e il calore danese.",
        "descriptionEs": "Una abuela de Jutlandia que enseña a través de las tradiciones y la calidez danesa.",
        "greetingEn": "Goddag, dear! Let me share the warmth of Danish with you.",
        "greetingDa": "Goddag, kære! Lad mig dele det danske sprogs varme med dig.",
        "greetingIt": "Goddag, caro! Lascia che condivida con te il calore della lingua danese.",
        "greetingEs": "¡Goddag, querido! Déjame compartir contigo la calidez del danés.",
        "color": "rose",
        "voice": {"voiceName": "da-DK-ChristelNeural"},
    },
    {
        "id": "james",
        "name": "James",
        "language": "en",
        "emoji": "🤵‍♂️",
        "imageUrl": "/hosts/james-1.jpg",
        "descriptionEn": "A London tour guide who brings English to life through British culture.",
        "descriptionDa": "En London-turistguide, der bringer engelsk til live gennem britisk kultur.",
        "descriptionIt": "Una guida turistica londinese che dà vita all'inglese attraverso la cultura britannica.",
        "descriptionEs": "Un guía turístico londinense que da vida al inglés a través de la cultura británica.",
        "greetingEn": "Good day! Shall we explore the English language together?",
        "greetingDa": "God dag! Skal vi udforske det engelske sprog sammen?",
        "greetingIt": "Buongiorno! Esploriamo insieme la lingua inglese?",
        "greetingEs": "¡Buen día! ¿Exploramos juntos el idioma inglés?",
        "color": "slate",
        "voice": {"voiceName": "en-GB-ThomasNeural"},
    },
    {
        "id": "emma",
        "name": "Emma",
        "language": "en",
        "emoji": "👩‍🎓",
        "imageUrl": "/hosts/emma-1.jpg",
        "descriptionEn": "An Oxford professor with a love for literature and etymology.",
        "descriptionDa": "En Oxford-professor med kærlighed til litteratur og etymologi.",
        "descriptionIt": "Una professoressa di Oxford appassionata di letteratura ed etimologia.",
        "descriptionEs": "Una profesora de Oxford apasionada por la literatura y la etimología.",
        "greetingEn": "Welcome! Let's delve into the nuances of English pronunciation.",
        "greetingDa": "Velkommen! Lad os dykke ned i nuancerne i engelsk udtale.",
        "greetingIt": "Benvenuto! Approfondiamo le sfumature della pronuncia inglese.",
        "greetingEs": "¡Bienvenido! Profundicemos en los matices de la pronunciación inglesa.",
        "color": "emerald",
        "voice": {"voiceName": "en-GB-SoniaNeural"},
    },
    {
        "id": "ryan",
        "name": "Ryan",
        "language": "en",
        "emoji": "🏄‍♂️",
        "imageUrl": "/hosts/ryan-1.jpg",
        "descriptionEn": "An Australian surfer who makes learning English fun and laid-back.",
        "descriptionDa": "En australsk surfer, der gør det sjovt og afslappet at lære engelsk.",
        "descriptionIt": "Un surfista australiano che rende l'apprendimento dell'inglese divertente e rilassato.",
        "descriptionEs": "Un surfista australiano que hace que aprender inglés sea divertido y relajado.",
        "greetingEn": "G'day mate! Let's have a crack at some English words!",
        "greetingDa": "G'day mate! Lad os prøve kræfter med nogle engelske ord!",
        "greetingIt": "G'day mate! Proviamo qualche parola inglese insieme!",
        "greetingEs": "¡G'day mate! ¡Probemos algunas palabras en inglés juntos!",
        "color": "orange",
        "voice": {"voiceName": "en-AU-WilliamMultilingualNeural"},
    },
    {
        "id": "margaret",
        "name": "Margaret",
        "language": "en",
        "emoji": "🧓",
        "imageUrl": "/hosts/margaret-1.jpg",
        "descriptionEn": "A Scottish grandmother who teaches through stories and wisdom.",
        "descriptionDa": "En skotsk bedstemor, der underviser gennem historier og visdom.",
        "descriptionIt": "Una nonna scozzese che insegna attraverso storie e saggezza.",
        "descriptionEs": "Una abuela escocesa que enseña a través de historias y sabiduría.",
        "greetingEn": "Hello, dear! Come sit down and let's practise some lovely English words.",
        "greetingDa": "Hej, kære! Kom og sæt dig, og lad os øve nogle dejlige engelske ord.",
        "greetingIt": "Ciao, caro! Siediti e esercitiamoci con qualche bella parola inglese.",
        "greetingEs": "¡Hola, querido! Siéntate y practiquemos algunas hermosas palabras en inglés.",
        "color": "violet",
        "voice": {"voiceName": "en-GB-LibbyNeural"},
    },
    # ── Spanish hosts ──
    {
        "id": "carlos",
        "name": "Carlos",
        "language": "es",
        "emoji": "👨‍🍳",
        "imageUrl": "/hosts/carlos-1.jpg",
        "descriptionEn": "A Madrid chef who teaches Spanish through the flavours of tapas and tradition.",
        "descriptionDa": "En kok fra Madrid, der underviser i spansk gennem tapas og tradition.",
        "descriptionIt": "Uno chef di Madrid che insegna lo spagnolo attraverso i sapori delle tapas e la tradizione.",
        "descriptionEs": "Un chef madrileño que enseña español a través de los sabores de las tapas y la tradición.",
        "greetingEn": "¡Hola! Let's spice up your Spanish with some tasty words!",
        "greetingDa": "¡Hola! Lad os krydre dit spanske med nogle lækre ord!",
        "greetingIt": "¡Hola! Aggiungiamo un po' di sapore al tuo spagnolo con parole gustose!",
        "greetingEs": "¡Hola! ¡Vamos a darle sabor a tu español con unas palabras deliciosas!",
        "color": "red",
        "voice": {"voiceName": "es-ES-AlvaroNeural"},
    },
    {
        "id": "lucia",
        "name": "Lucía",
        "language": "es",
        "emoji": "👩‍🏫",
        "imageUrl": "/hosts/lucia-1.jpg",
        "descriptionEn": "A Barcelona professor with a passion for clear pronunciation and literature.",
        "descriptionDa": "En professor fra Barcelona med passion for tydelig udtale og litteratur.",
        "descriptionIt": "Una professoressa di Barcellona con la passione per la pronuncia chiara e la letteratura.",
        "descriptionEs": "Una profesora de Barcelona apasionada por la pronunciación clara y la literatura.",
        "greetingEn": "¡Buenos días! Let's perfect your Spanish pronunciation together.",
        "greetingDa": "¡Buenos días! Lad os perfektionere din spanske udtale sammen.",
        "greetingIt": "¡Buenos días! Perfezzioniamo insieme la tua pronuncia spagnola.",
        "greetingEs": "¡Buenos días! Perfeccionemos juntos tu pronunciación en español.",
        "color": "blue",
        "voice": {"voiceName": "es-ES-ElviraNeural"},
    },
    {
        "id": "pablo",
        "name": "Pablo",
        "language": "es",
        "emoji": "🧑‍🎤",
        "imageUrl": "/hosts/pablo-1.jpg",
        "descriptionEn": "A laid-back Mexican student who makes learning Spanish fun and natural.",
        "descriptionDa": "En afslappet mexicansk studerende, der gør det sjovt og naturligt at lære spansk.",
        "descriptionIt": "Uno studente messicano rilassato che rende l'apprendimento dello spagnolo divertente e naturale.",
        "descriptionEs": "Un estudiante mexicano relajado que hace que aprender español sea divertido y natural.",
        "greetingEn": "¡Qué onda! Ready to speak Spanish like a local? ¡Vámonos!",
        "greetingDa": "¡Qué onda! Klar til at tale spansk som en lokal? ¡Vámonos!",
        "greetingIt": "¡Qué onda! Pronto a parlare spagnolo come un locale? ¡Vámonos!",
        "greetingEs": "¡Qué onda! ¿Listo para hablar español como un local? ¡Vámonos!",
        "color": "orange",
        "voice": {"voiceName": "es-MX-JorgeNeural"},
    },
    {
        "id": "carmen",
        "name": "Carmen",
        "language": "es",
        "emoji": "👵",
        "imageUrl": "/hosts/carmen-1.jpg",
        "descriptionEn": "A warm Andalusian grandmother who teaches through stories and tradition.",
        "descriptionDa": "En varm andalusisk bedstemor, der underviser gennem historier og tradition.",
        "descriptionIt": "Una calda nonna andalusa che insegna attraverso storie e tradizioni.",
        "descriptionEs": "Una cálida abuela andaluza que enseña a través de historias y tradiciones.",
        "greetingEn": "¡Bienvenido, cariño! Let me share the beauty of Spanish with you.",
        "greetingDa": "¡Bienvenido, cariño! Lad mig dele skønheden ved det spanske sprog med dig.",
        "greetingIt": "¡Bienvenido, cariño! Lascia che ti mostri la bellezza dello spagnolo.",
        "greetingEs": "¡Bienvenido, cariño! Déjame compartir contigo la belleza del español.",
        "color": "amber",
        "voice": {"voiceName": "es-ES-ElviraNeural"},
    },
]

HOST_IDS = [host["id"] for host in HOSTS]


def get_host(host_id: str) -> dict:
    return next((host for host in HOSTS if host["id"] == host_id), HOSTS[0])
